# Render.yaml - Configuración para deployment en Render con Docker
# IMPORTANTE: Los servicios se deben crear en este orden específico
services:
  # 1. Base de datos PostgreSQL (CREAR PRIMERO)
  - type: pserv
    name: edp-database
    databaseName: edp_mvp_db
    plan: starter

  # 2. Redis para cache y Celery (CREAR SEGUNDO)
  - type: redis
    name: edp-redis
    ipAllowList: []
    plan: starter

  # 3. Aplicación web principal (CREAR ÚLTIMO)
  - type: web
    name: edp-mvp-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: edp-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: edp-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: edp-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: edp-redis
          property: connectionString

  # Worker de Celery (opcional, puede ejecutarse en el mismo servicio web)
  - type: worker
    name: edp-celery-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A edp_mvp.app.celery worker --loglevel=info --concurrency=1"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: edp-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: edp-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: edp-redis
          property: connectionString
